// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebhookAlbatroz.Context;

#nullable disable

namespace WebhookAlbatroz.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebhookAlbatroz.Entity.DocumentoIntegracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenidoXML")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("CufeExtraido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaDescarga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NitEmisor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UrlOrigen")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NitEmisor")
                        .HasDatabaseName("IX_DocumentoIntegracion_NitEmisor");

                    b.HasIndex("TrackId")
                        .IsUnique()
                        .HasDatabaseName("UX_DocumentoIntegracion_TrackId");

                    b.ToTable("DocumentosIntegracion", (string)null);
                });

            modelBuilder.Entity("WebhookAlbatroz.Entity.EventoRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CodigoMotivo")
                        .HasColumnType("int");

                    b.Property<string>("Cude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cufe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Glosario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NitEmisor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UrlIntegracion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UrlPDF")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UrlRespuestaDian")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UrlUbl")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FechaHora")
                        .HasDatabaseName("IX_EventoRegistro_FechaHora");

                    b.HasIndex("NitEmisor")
                        .HasDatabaseName("IX_EventoRegistro_NitEmisor");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("IX_EventoRegistro_TrackId");

                    b.ToTable("EventosRegistrados", (string)null);
                });

            modelBuilder.Entity("WebhookAlbatroz.Entity.SaleInfoRQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TechnologyField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("channelField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dateBookField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eventoField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("includeFlightsField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("includeHotelsField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("includeInsuranceField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("includePackageField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("locField")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("portalField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stringincludeCarsField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SaleInfoRQ", (string)null);
                });

            modelBuilder.Entity("WebhookAlbatroz.Entity.WebhookEventoSuscrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WebhookSuscripcionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WebhookSuscripcionId");

                    b.ToTable("WebhookEventosSuscritos", (string)null);
                });

            modelBuilder.Entity("WebhookAlbatroz.Entity.WebhookSuscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaUltimoEvento")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReintentosMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("SecretKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TimeoutSegundos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<string>("UltimoNitEmisor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UltimoTrackId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("WebhookSuscripciones", (string)null);
                });

            modelBuilder.Entity("WebhookAlbatroz.Entity.WebhookEventoSuscrito", b =>
                {
                    b.HasOne("WebhookAlbatroz.Entity.WebhookSuscripcion", "WebhookSuscripcion")
                        .WithMany("EventosSuscritos")
                        .HasForeignKey("WebhookSuscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebhookSuscripcion");
                });

            modelBuilder.Entity("WebhookAlbatroz.Entity.WebhookSuscripcion", b =>
                {
                    b.Navigation("EventosSuscritos");
                });
#pragma warning restore 612, 618
        }
    }
}
